//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomaticQuestionPaperGeneration.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutomaticQuestionPaperContext : DbContext
    {
        public AutomaticQuestionPaperContext()
            : base("name=AutomaticQuestionPaperModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<ExamPaper> ExamPapers1 { get; set; }
    }
}
