//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomaticQuestionPaperGeneration.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionId { get; set; }
        public string QuestionText { get; set; }
        public int QuestionDifficultyLevel { get; set; }
        public int ChapterId { get; set; }
    
        public virtual Chapter Chapter { get; set; }
    }
}
