//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomaticQuestionPaperGeneration.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffId { get; set; }
        public string StaffFullName { get; set; }
        public string StaffAddress { get; set; }
        public string StaffGender { get; set; }
        public string StaffPhoneNumber { get; set; }
        public string StaffEmailAddress { get; set; }
        public string StaffPassword { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
