//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;

namespace AutomatedQuestionPaper.Models
{
    [MetadataType(typeof(AnswerMetaData))]
    public partial class Answer
    {

    }

    public partial class AnswerMetaData
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Range(0, int.MaxValue, ErrorMessage = "Please enter valid Number")]

        public Nullable<int> QuestionId { get; set; }

        
        public string Name { get; set; }

        public Nullable<bool> IsCorrect { get; set; }

        public int DisplayOrder { get; set; }
    
        public virtual QuestionMetaData Question { get; set; }
    }
}
