//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AutomatedQuestionPaper.Models.ModelsMetaData
{
    using System;

    public partial class ExamPaper
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [DisplayName("Staff ID")]
        public Nullable<int> StaffId { get; set; }

        [DataType(DataType.Text)]
        [DisplayName("Paper name")]
        [Required]
        public string PaperName { get; set; }

        [DisplayName("Paper value")]
        [Required]
        public byte[] PaperValue { get; set; }
    }
}
