//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AutomatedQuestionPaper.Models
{
    public partial class Admin
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("Username")]
        [MaxLengthAttribute(256)]
        [DataType(DataType.Text)]
        [Required]
        public string username { get; set; }

        [DisplayName("Password")]
        [MaxLengthAttribute(256)]
        [DataType(DataType.Password)]
        [Required]
        public string password { get; set; }
    }
}
