//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using AutomatedQuestionPaper.Models.ModelsMetaData;

namespace AutomatedQuestionPaper.Models
{
    using System;
    using System.Collections.Generic;
    
    [MetadataType(typeof(AdminMetaData))]
    public partial class Admin
    {
        public int id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
