//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AutomatedQuestionPaper.Models.ModelsMetaData;

namespace AutomatedQuestionPaper.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(AnswerMetaData))]
    public partial class Answer
    {
        public int Id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsCorrect { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
