//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace AutomatedQuestionPaper.Models
{
    public partial class Chapter
    {
        [Key]
        public int Id { get; set; }
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
