//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AutomatedQuestionPaper.Models
{
    public partial class QuestionType
    {
        [Key]
        public int Id { get; set; }

        [DisplayName("Name")]
        [MaxLength(256)]
        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        public string IsActive { get; set; }
    }
}
