//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AutomatedQuestionPaper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semister
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semister()
        {
            this.TeacherCourses = new HashSet<TeacherCourse>();
        }
    
        [Key]
        public int Id { get; set; }

        [DisplayName("Semister")]
        [MaxLength(256)]
        [DataType(DataType.Text)]
        [Required]
        public string semister { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeacherCourse> TeacherCourses { get; set; }
    }
}
