//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using AutomatedQuestionPaper.Models.ModelsMetaData;

namespace AutomatedQuestionPaper.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(StaffCourseMetaData))]
    public partial class StaffCourse
    {
        public int Id { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public Nullable<int> CourseId { get; set; }
    }
}
